# Generated by Django 3.0.2 on 2020-03-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='darkColorScheme',
            field=models.BooleanField(default=False),
        ),
    ]
