# Generated by Django 3.0.2 on 2020-03-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_darkcolorscheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='darkColorScheme',
            field=models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark')], default='Light', max_length=10),
        ),
    ]
