# Generated by Django 3.0.2 on 2020-01-25 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_title', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=25)),
                ('project_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_title', models.CharField(max_length=25)),
                ('team_projectid', models.ManyToManyField(to='restAPI.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=25)),
                ('review_defectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.Defect')),
                ('review_projectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.Project')),
                ('review_toolid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.Tool')),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_firstname', models.CharField(max_length=25)),
                ('engineer_teamid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.Team')),
            ],
        ),
        migrations.AddField(
            model_name='defect',
            name='defect_employeeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.Engineer'),
        ),
        migrations.AddField(
            model_name='defect',
            name='defect_projectid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.Project'),
        ),
        migrations.AddField(
            model_name='defect',
            name='defect_toolid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.Tool'),
        ),
    ]
