# Generated by Django 3.0.2 on 2020-02-04 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('racf', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PhaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('productOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.Engineer')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOpened', models.DateField()),
                ('dateClosed', models.DateField()),
                ('tag', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=25)),
                ('url', models.URLField()),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.Project')),
                ('whereFound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.PhaseType')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('ProjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='teamID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.Team'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='teamID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.Team'),
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOpened', models.DateField()),
                ('dateClosed', models.DateField()),
                ('tag', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=25)),
                ('url', models.URLField()),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.Project')),
                ('whereFound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.PhaseType')),
            ],
        ),
    ]
