# Generated by Django 3.0.2 on 2020-01-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_defectid',
        ),
        migrations.AddField(
            model_name='review',
            name='review_defectid',
            field=models.ManyToManyField(to='restAPI.Defect'),
        ),
    ]
