# Generated by Django 3.0.2 on 2020-02-04 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectnumber',
            old_name='ProjectID',
            new_name='projectID',
        ),
    ]
