# Generated by Django 3.0.2 on 2020-03-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='tag',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='defect',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='tag',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
