# Generated by Django 3.0.2 on 2020-02-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0002_auto_20200204_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='dateClosed',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='dateClosed',
            field=models.DateField(blank=True),
        ),
    ]
